name: Bot Minecraft
on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install mineflayer

      - name: Create bot script
        run: |
          cat << 'EOF' > index.js
          const mineflayer = require('mineflayer');
          const bot = mineflayer.createBot({
            host: 'PixelowyMc.aternos.me',
            port: 14728, // <-- WPISZ AKTUALNY PORT Z ATERNOSA
            username: 'kuba21',
            auth: 'offline',
            version: '1.21.11'
          });

          bot.once('spawn', () => {
            console.log("Bot pomyślnie dołączył do serwera!");
          });

          bot.on('error', err => console.log("Błąd:", err));
          bot.on('kicked', reason => console.log("Wyrzucono z serwera:", reason));
          EOF

      - name: Run bot
        run: node index.js
        
        
